/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as PrivateTransactionsRouteImport } from './routes/_private/transactions'
import { Route as PrivateReportsRouteImport } from './routes/_private/reports'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateMeiLimitRouteImport } from './routes/_private/mei-limit'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_public/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateTransactionsRoute = PrivateTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateReportsRoute = PrivateReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateMeiLimitRoute = PrivateMeiLimitRouteImport.update({
  id: '/mei-limit',
  path: '/mei-limit',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/mei-limit': typeof PrivateMeiLimitRoute
  '/profile': typeof PrivateProfileRoute
  '/reports': typeof PrivateReportsRoute
  '/transactions': typeof PrivateTransactionsRoute
  '/auth': typeof PublicAuthRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/mei-limit': typeof PrivateMeiLimitRoute
  '/profile': typeof PrivateProfileRoute
  '/reports': typeof PrivateReportsRoute
  '/transactions': typeof PrivateTransactionsRoute
  '/auth': typeof PublicAuthRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/mei-limit': typeof PrivateMeiLimitRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/reports': typeof PrivateReportsRoute
  '/_private/transactions': typeof PrivateTransactionsRoute
  '/_public/auth': typeof PublicAuthRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/mei-limit'
    | '/profile'
    | '/reports'
    | '/transactions'
    | '/auth'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/mei-limit'
    | '/profile'
    | '/reports'
    | '/transactions'
    | '/auth'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_private/dashboard'
    | '/_private/mei-limit'
    | '/_private/profile'
    | '/_private/reports'
    | '/_private/transactions'
    | '/_public/auth'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicAuthRoute: typeof PublicAuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/transactions': {
      id: '/_private/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof PrivateTransactionsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/reports': {
      id: '/_private/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof PrivateReportsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/mei-limit': {
      id: '/_private/mei-limit'
      path: '/mei-limit'
      fullPath: '/mei-limit'
      preLoaderRoute: typeof PrivateMeiLimitRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateMeiLimitRoute: typeof PrivateMeiLimitRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateReportsRoute: typeof PrivateReportsRoute
  PrivateTransactionsRoute: typeof PrivateTransactionsRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateMeiLimitRoute: PrivateMeiLimitRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateReportsRoute: PrivateReportsRoute,
  PrivateTransactionsRoute: PrivateTransactionsRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicAuthRoute: PublicAuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
